// SessionContext.tsx
// Manages the customer's table session and participant identity.
// Reads ?table= and ?token= from URL, validates the QR token against the backend,
// creates/fetches a session, and registers a participant so cart + checkout work correctly.

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '../lib/supabase';

// ─── Error codes ──────────────────────────────────────────────────────────────
/** Returned when the backend rejects the QR token (400 or 401). */
const ERROR_INVALID_QR = 'INVALID_QR';

interface SessionContextValue {
  sessionId: string | null;
  participantId: string | null;
  tableNumber: string | null;
  isReady: boolean;
  error: string | null;
}

const SessionContext = createContext<SessionContextValue>({
  sessionId: null,
  participantId: null,
  tableNumber: null,
  isReady: false,
  error: null,
});

/** Generate or reuse a stable device ID stored in localStorage */
const getDeviceId = (): string => {
  let deviceId = localStorage.getItem('device_id');
  if (!deviceId) {
    deviceId = crypto.randomUUID();
    localStorage.setItem('device_id', deviceId);
  }
  return deviceId;
};

// ─── Invalid QR Screen ────────────────────────────────────────────────────────
const InvalidQrScreen: React.FC = () => (
  <div style={{
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 24px',
    textAlign: 'center',
    backgroundColor: 'var(--bg-app, #f4f0ec)',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  }}>
    {/* Icon */}
    <div style={{
      width: '80px',
      height: '80px',
      borderRadius: '50%',
      backgroundColor: '#fee2e2',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: '24px',
    }}>
      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <line x1="12" y1="8" x2="12" y2="12" />
        <line x1="12" y1="16" x2="12.01" y2="16" />
      </svg>
    </div>

    {/* Message */}
    <h1 style={{
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#1a100e',
      margin: '0 0 12px 0',
    }}>
      Invalid QR Code
    </h1>
    <p style={{
      fontSize: '15px',
      color: '#6e6e6e',
      lineHeight: '1.6',
      maxWidth: '300px',
      margin: '0 0 32px 0',
    }}>
      This QR code isn&apos;t valid. Please ask staff for help — they can provide you with a new one.
    </p>

    {/* Blaine Wings branding */}
    <p style={{
      fontSize: '12px',
      color: '#aaa',
      textTransform: 'uppercase',
      letterSpacing: '1px',
    }}>
      Blaine Wings · Unlimited Wings
    </p>
  </div>
);

// ─── Generic Error Screen ─────────────────────────────────────────────────────
const SessionErrorScreen: React.FC<{ message: string }> = ({ message }) => (
  <div style={{
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 24px',
    textAlign: 'center',
    backgroundColor: 'var(--bg-app, #f4f0ec)',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  }}>
    <h1 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1a100e', margin: '0 0 12px 0' }}>
      Something went wrong
    </h1>
    <p style={{ fontSize: '14px', color: '#6e6e6e', maxWidth: '280px' }}>
      {message}
    </p>
  </div>
);

// ─── Provider ─────────────────────────────────────────────────────────────────
export const SessionProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [sessionId, setSessionId] = useState<string | null>(
    () => localStorage.getItem('session_id')
  );
  const [participantId, setParticipantId] = useState<string | null>(
    () => localStorage.getItem('participant_id')
  );
  const [tableNumber, setTableNumber] = useState<string | null>(null);
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const init = async () => {
      try {
        // Read table number and QR token from URL
        // QR codes generated by admin encode: /menu/:tableNumber?token=:qrToken
        const params = new URLSearchParams(window.location.search);
        const table = params.get('table') || localStorage.getItem('table_number') || '1';
        const token = params.get('token');

        setTableNumber(table);
        localStorage.setItem('table_number', table);

        const apiUrl = import.meta.env.VITE_API_URL;
        const deviceId = getDeviceId();

        // Step 1: Get or create a table session from the backend.
        // The backend now REQUIRES ?token= for the security check.
        let currentSessionId = sessionId;
        if (!currentSessionId) {
          // Build the session URL — always include token if present in the URL.
          const sessionUrl = token
            ? `${apiUrl}/api/tables/${table}/session?token=${encodeURIComponent(token)}`
            : `${apiUrl}/api/tables/${table}/session`;

          const sessionRes = await fetch(sessionUrl, {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' },
          });

          if (sessionRes.status === 400 || sessionRes.status === 401) {
            // The backend explicitly rejected the QR token — show the user-facing error screen.
            setError(ERROR_INVALID_QR);
            setIsReady(true);
            return;
          }

          if (!sessionRes.ok) throw new Error('Could not create table session');

          const sessionJson = await sessionRes.json();
          currentSessionId = sessionJson.data?.session?.id ?? sessionJson.data?.session_id ?? sessionJson.data?.id ?? sessionJson.session_id;

          if (!currentSessionId || currentSessionId === 'undefined') {
            throw new Error('No session_id returned from backend');
          }
          localStorage.setItem('session_id', currentSessionId);
          setSessionId(currentSessionId);
        } else if (currentSessionId === 'undefined') {
          localStorage.removeItem('session_id');
          setSessionId(null);
          throw new Error('Invalid session state. Please refresh.');
        }

        // Step 2: Register participant in Supabase (if not already done)
        let currentParticipantId = participantId;
        if (!currentParticipantId) {
          const { data: existing } = await supabase
            .from('session_participants')
            .select('id')
            .eq('session_id', currentSessionId)
            .eq('device_id', deviceId)
            .maybeSingle();

          if (existing?.id) {
            currentParticipantId = existing.id;
          } else {
            const { data: inserted, error: insertError } = await supabase
              .from('session_participants')
              .insert({ session_id: currentSessionId, device_id: deviceId, name: 'Guest' })
              .select('id')
              .single();

            if (insertError) throw insertError;
            currentParticipantId = inserted.id;
          }

          localStorage.setItem('participant_id', currentParticipantId!);
          setParticipantId(currentParticipantId);
        }

        setIsReady(true);
      } catch (err: any) {
        console.error('Session init error:', err);
        setError(err.message || 'Failed to initialize session');
        setIsReady(true); // Still mark ready so app doesn't hang
      }
    };

    init();
  }, []);

  // ── Blocking error screens ─────────────────────────────────────────────────
  // Only shown when the session is ready but has a fatal error.
  // This prevents the app from rendering on top of a broken session.
  if (isReady && error === ERROR_INVALID_QR) {
    return <InvalidQrScreen />;
  }

  if (isReady && error && error !== 'Failed to initialize session') {
    // For any other hard error (not the generic "try again" case), show a generic screen.
    return <SessionErrorScreen message={error} />;
  }

  return (
    <SessionContext.Provider value={{ sessionId, participantId, tableNumber, isReady, error }}>
      {children}
    </SessionContext.Provider>
  );
};

export const useSession = (): SessionContextValue => {
  return useContext(SessionContext);
};

