// SessionContext.tsx
// Manages the customer's table session and participant identity.
// Reads ?table= and ?token= from URL, validates the QR token against the backend,
// creates/fetches a session, and registers a participant so cart + checkout work correctly.

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '../lib/supabase';

// ─── Error codes ──────────────────────────────────────────────────────────────
/** Returned when the backend rejects the QR token (400 or 401). */
const ERROR_INVALID_QR = 'INVALID_QR';

interface SessionContextValue {
  sessionId: string | null;
  participantId: string | null;
  tableNumber: string | null;
  isReady: boolean;
  error: string | null;
}

const SessionContext = createContext<SessionContextValue>({
  sessionId: null,
  participantId: null,
  tableNumber: null,
  isReady: false,
  error: null,
});

/** Generate or reuse a stable device ID stored in localStorage */
const getDeviceId = (): string => {
  let deviceId = localStorage.getItem('device_id');
  if (!deviceId) {
    deviceId = crypto.randomUUID();
    localStorage.setItem('device_id', deviceId);
  }
  return deviceId;
};

// ─── Invalid QR Screen ────────────────────────────────────────────────────────
const InvalidQrScreen: React.FC = () => (
  <div style={{
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 24px',
    textAlign: 'center',
    backgroundColor: 'var(--bg-app, #f4f0ec)',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  }}>
    {/* Icon */}
    <div style={{
      width: '80px',
      height: '80px',
      borderRadius: '50%',
      backgroundColor: '#fee2e2',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: '24px',
    }}>
      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <line x1="12" y1="8" x2="12" y2="12" />
        <line x1="12" y1="16" x2="12.01" y2="16" />
      </svg>
    </div>

    {/* Message */}
    <h1 style={{
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#1a100e',
      margin: '0 0 12px 0',
    }}>
      Invalid QR Code
    </h1>
    <p style={{
      fontSize: '15px',
      color: '#6e6e6e',
      lineHeight: '1.6',
      maxWidth: '300px',
      margin: '0 0 32px 0',
    }}>
      This QR code isn&apos;t valid. Please ask staff for help — they can provide you with a new one.
    </p>

    {/* Blaine Wings branding */}
    <p style={{
      fontSize: '12px',
      color: '#aaa',
      textTransform: 'uppercase',
      letterSpacing: '1px',
    }}>
      Blaine Wings · Unlimited Wings
    </p>
  </div>
);

// ─── Generic Error Screen ─────────────────────────────────────────────────────
const SessionErrorScreen: React.FC<{ message: string }> = ({ message }) => (
  <div style={{
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 24px',
    textAlign: 'center',
    backgroundColor: 'var(--bg-app, #f4f0ec)',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  }}>
    <h1 style={{ fontSize: '20px', fontWeight: 'bold', color: '#1a100e', margin: '0 0 12px 0' }}>
      Something went wrong
    </h1>
    <p style={{ fontSize: '14px', color: '#6e6e6e', maxWidth: '280px' }}>
      {message}
    </p>
  </div>
);

// ─── Provider ─────────────────────────────────────────────────────────────────
export const SessionProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [sessionId, setSessionId] = useState<string | null>(
    () => localStorage.getItem('session_id')
  );
  const [participantId, setParticipantId] = useState<string | null>(
    () => localStorage.getItem('participant_id')
  );
  const [tableNumber, setTableNumber] = useState<string | null>(null);
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const init = async () => {
      try {
        // Read table number and QR token from URL
        // QR codes generated by admin encode: /menu/:tableNumber?token=:qrToken
        const params = new URLSearchParams(window.location.search);
        
        // Parse table number from path if URL format is /menu/:tableNumber
        const pathParts = window.location.pathname.split('/');
        const pathTable = (pathParts[1] === 'menu' && pathParts[2]) ? pathParts[2] : null;

        const rawTable = params.get('table') || pathTable || localStorage.getItem('table_number') || 'Table 1';
        const table = decodeURIComponent(rawTable);
        const token = params.get('token');

        console.log('[SessionInit] Table:', table, 'Token:', token);

        setTableNumber(table);
        localStorage.setItem('table_number', table);

        const apiUrl = import.meta.env.VITE_API_URL;
        const deviceId = getDeviceId();

        // Step 1: Get or create a table session from the backend.
        let currentSessionId = sessionId;
        // If a new QR token is in the URL, force fetching a new session from the backend
        if (token) {
          currentSessionId = null;
        }

        if (!currentSessionId) {
          // Build the session URL — always include token if present in the URL.
          const sessionUrl = token
            ? `${apiUrl}/api/tables/${encodeURIComponent(table)}/session?token=${encodeURIComponent(token)}`
            : `${apiUrl}/api/tables/${encodeURIComponent(table)}/session`;

          let sessionJson: any = null;
          try {
            const sessionRes = await fetch(sessionUrl, {
              method: 'GET',
              headers: { 'Content-Type': 'application/json' },
            });

            if (sessionRes.status === 400 || sessionRes.status === 401) {
              if (token) {
                // The backend explicitly rejected a scanned QR token — show the error screen.
                setError(ERROR_INVALID_QR);
                setIsReady(true);
                return;
              } else {
                // No token was provided in the URL (e.g. direct load of localhost).
                // Fall back to a local dev session.
                console.warn('Backend rejected session without token. Falling through to local dev session.');
              }
            }

            if (sessionRes.ok) {
              sessionJson = await sessionRes.json();
            }
          } catch (fetchErr) {
            // Network error or the /tables endpoint isn't deployed yet.
            // Fall through to use a local dev session below.
            console.warn('Session API unavailable, using local dev session:', fetchErr);
          }

          if (sessionJson) {
            currentSessionId = sessionJson.data?.session?.id ?? sessionJson.data?.session_id ?? sessionJson.data?.id ?? sessionJson.session_id;
          }

          // If we couldn't get a real session ID from the backend, use a local fallback.
          // This keeps the app usable for local development without needing a QR scan.
          if (!currentSessionId || currentSessionId === 'undefined') {
            currentSessionId = `local-dev-session-${table}`;
            console.warn('Using local dev session ID. Real orders will not be placed.');
          }

          localStorage.setItem('session_id', currentSessionId);
          setSessionId(currentSessionId);
        } else if (currentSessionId === 'undefined') {
          localStorage.removeItem('session_id');
          setSessionId(null);
          throw new Error('Invalid session state. Please refresh.');
        }

        // Step 2: Register participant in Supabase (if not already done).
        // Skip this for local dev sessions since they won't exist in the DB.
        let currentParticipantId = participantId;
        
        if (!currentSessionId.startsWith('local-dev-session')) {
          // Always check if we have a valid participant for the CURRENT real session.
          // We query by session_id and device_id.
          const { data: existing } = await supabase
            .from('session_participants')
            .select('id')
            .eq('session_id', currentSessionId)
            .eq('device_id', deviceId)
            .maybeSingle();

          if (existing?.id) {
            currentParticipantId = existing.id;
          } else {
            const { data: inserted, error: insertError } = await supabase
              .from('session_participants')
              .insert({ session_id: currentSessionId, device_id: deviceId, name: 'Guest' })
              .select('id')
              .single();

            if (insertError) throw insertError;
            currentParticipantId = inserted.id;
          }

          localStorage.setItem('participant_id', currentParticipantId!);
          setParticipantId(currentParticipantId);
        } else {
          // Local dev fallback participant ID
          if (!currentParticipantId || !currentParticipantId.startsWith('local-dev-participant')) {
            currentParticipantId = `local-dev-participant-${deviceId}`;
            localStorage.setItem('participant_id', currentParticipantId);
            setParticipantId(currentParticipantId);
          }
        }

        setIsReady(true);
      } catch (err: any) {
        console.error('Session init error:', err);
        setError(err.message || 'Failed to initialize session');
        setIsReady(true); // Still mark ready so app doesn't hang
      }
    };

    init();
  }, []);

  // ── Blocking error screens ─────────────────────────────────────────────────
  // Only shown when the session is ready but has a fatal error.
  // This prevents the app from rendering on top of a broken session.
  if (isReady && error === ERROR_INVALID_QR) {
    return <InvalidQrScreen />;
  }

  if (isReady && error && error !== 'Failed to initialize session') {
    // For any other hard error (not the generic "try again" case), show a generic screen.
    return <SessionErrorScreen message={error} />;
  }

  return (
    <SessionContext.Provider value={{ sessionId, participantId, tableNumber, isReady, error }}>
      {children}
    </SessionContext.Provider>
  );
};

export const useSession = (): SessionContextValue => {
  return useContext(SessionContext);
};

